name: Run Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    if: github.repository == '{{cookiecutter.gh_repo_slug}}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ '{{ matrix.python-version }}' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ '{{ matrix.python-version }}' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-report=html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ '{{ secrets.CODECOV_TOKEN }}' }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
